### ISSUE TITLE
Can't execute the rake tasks - execute_batch and generate_script.

### ISSUE THREAD

**Issue by ykulkarnidia** [onc-healthit/inferno-community#485]
I get following error, when I execute rake task 

` docker exec -it inferno bundle exec rake inferno:execute_batch[test.json]`
```

10:56:28  rake aborted!
10:56:28  NoMethodError: undefined method `fhir_version' for nil:NilClass
10:56:28  lib/tasks/tasks.rake:432:in `block (2 levels) in <top (required)>'
10:56:28  /usr/local/bundle/ruby/2.5.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
10:56:28  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
10:56:28  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
10:56:28  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
10:56:28  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
10:56:28  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
10:56:28  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
10:56:28  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
10:56:28  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
10:56:28  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
10:56:28  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
10:56:28  /usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
10:56:28  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
10:56:28  /usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
10:56:28  /usr/local/bundle/bin/bundle:23:in `load'
10:56:28  /usr/local/bundle/bin/bundle:23:in `<main>'
10:56:28  Tasks: TOP => inferno:execute_batch
10:56:28  (See full trace by running task with --trace)
10:56:28  Found orphan containers (docker_inferno_bdt_service_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
```
Does `Inferno::StartupTasks.load_all_modules` need to called before starting up the rake tasks?

**Comment by t-zhao** [comment]
Got the same issue, adding `Inferno::StartupTasks.load_all_modules` could resolve it.

**Comment by Jammjammjamm** [comment]
Just opened a PR that should resolve this issue.
